# Generated by Django 5.2.8 on 2026-09-15 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0012_delete_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tickets',
            field=models.ManyToManyField(blank=True, to='ticketing.ticket'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_ID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
