# Generated by Django 5.2.8 on 2026-04-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(blank=True, upload_to='static/img/committee/')),
                ('order', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PastConcert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField(help_text='Rough date of concert')),
                ('venue', models.CharField(blank=True, max_length=200, null=True)),
                ('conductor', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('programme', models.TextField(blank=True, help_text='List of pieces performed')),
            ],
            options={
                'verbose_name_plural': 'Past Concerts',
                'ordering': ['-date'],
            },
        ),
    ]
