# Generated by Django 5.2.8 on 2026-09-15 00:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditionSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "Strings" or "Brass, Wind and Percussion (BWP)"', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Shown under the section name, e.g. what to prepare')),
                ('booking_url', models.CharField(blank=True, help_text='In Google Calendar, open the appointment schedule, click Share → Website embed, and paste the inline embed code (or just its src link) here.', max_length=1000, verbose_name='Google booking page embed link')),
                ('order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
                ('is_published', models.BooleanField(default=False, help_text='Only published sections appear on the Join Us page')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AuditionExcerpt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. "Violin excerpts"', max_length=200)),
                ('pdf', models.FileField(upload_to='auditions/excerpts/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excerpts', to='main_site.auditionsection')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='AuditionDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=200)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='main_site.auditionsection')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
