# Generated by Django 5.2.8 on 2026-09-15 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0002_auditionsection_auditionexcerpt_auditiondate'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditionsection',
            name='form_url',
            field=models.URLField(blank=True, help_text='Link to the audition form (e.g. a Google Form) that applicants fill in before booking', max_length=500, verbose_name='Audition form link'),
        ),
    ]
