"""
Django settings for NovaKelvin project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') != 'False'

ALLOWED_HOSTS = ["*"]
CSRF_TRUSTED_ORIGINS = ["https://kelvin-symphony.co.uk","http://127.0.0.1","https://staging.kelvin-symphony.co.uk","https://www.kelvin-symphony.co.uk"]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main_site.apps.MainSiteConfig',
    "tailwind",
    "theme",
    "ticketing",
    'rest_framework',  # Add Django Rest Framework
    'api',  # Add your app
    'django_saml2_auth',
]

TAILWIND_APP_NAME = "theme"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'NovaKelvin.middleware.UnderConstructionMiddleware',
]

ROOT_URLCONF = 'NovaKelvin.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'NovaKelvin.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.environ.get('POSTGRES_DB'),
        'USER': os.environ.get('POSTGRES_USER'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD'),
        'HOST': os.environ.get('PGHOST'),
        'PORT': os.environ.get('PGPORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]
# for production later:
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = '/media/'
MEDIA_ROOT = '/app/media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
}

STRIPE_SECRET_KEY = os.environ.get('STRIPE_SECRET_KEY')
STRIPE_PUBLISHABLE_KEY = os.environ.get('STRIPE_PUBLISHABLE_KEY')
STRIPE_WEBHOOK_SECRET = os.environ.get("STRIPE_WEBHOOK_SECRET")

# Return URL for Stripe checkout (adjust to your frontend URL)
STRIPE_RETURN_URL = os.environ.get("STRIPE_RETURN_URL")

if DEBUG:
    # Add django_browser_reload only in DEBUG mode
    INSTALLED_APPS += ["django_browser_reload"]
    # Add django_browser_reload middleware only in DEBUG mode
    MIDDLEWARE += [
        "django_browser_reload.middleware.BrowserReloadMiddleware",
    ]

SAML2_AUTH = {
    # Paste the metadata URL from Google Admin here
    # 'METADATA_AUTO_CONF_URL': 'https://accounts.google.com/o/saml2/idp?idpid=C03eq3bhc',
    'METADATA_LOCAL_FILE_PATH': BASE_DIR / 'saml' / 'GoogleIDPMetadata.xml',
    'ASSERTION_URL': 'https://cope-infringement-trinity-follow.trycloudflare.com/',  # Your site's base URL
    'ENTITY_ID': 'https://cope-infringement-trinity-follow.trycloudflare.com/sso/acs/',

    # Google sends email as the NameID, so map accordingly
    'ATTRIBUTES_MAP': {
        'email': 'user.email',
        'first_name': 'user.first_name',
        'last_name': 'user.last_name',
        'username': 'user.email',  # Use email as username
    },

    # Google doesn't send a token attribute, so disable this
    'TOKEN_REQUIRED': False,

    # Google signs responses but not always assertions individually
    'WANT_ASSERTIONS_SIGNED': False,
    'WANT_RESPONSE_SIGNED': True,
    'AUTHN_REQUESTS_SIGNED': False,  # Google doesn't require signed requests
    'LOGOUT_REQUESTS_SIGNED': False,

    'DEFAULT_NEXT_URL': '/dashboard/',  # Where to send users after login
    'CREATE_USER': True,
    'NEW_USER_PROFILE': {
        'USER_GROUPS': [],
        'ACTIVE_STATUS': True,
        'STAFF_STATUS': False,
        'SUPERUSER_STATUS': False,
    },

    'DEBUG': True,
    'LOGGING': {
        'version': 1,
        'handlers': {'stdout': {'class': 'logging.StreamHandler', 'level': 'DEBUG'}},
        'loggers': {'saml2': {'level': 'DEBUG'}},
        'root': {'level': 'DEBUG', 'handlers': ['stdout']},
    },
}
